sudo          : false
addons:
  ssh_known_hosts: ssh.suiram.org
language      : node_js
node_js       :
  - "6"

before_script :
  - "npm install -g webpack"


script        :
  - "npm install"
  - "npm run compile"

deploy :
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: develop
